### ISSUE TITLE
FabricException occured

### ISSUE THREAD

**Issue by matterai** [loekd/ServiceFabric.BackupRestore#5]
Hello!

I am using you tool for backup our internal Reliable storages and currently I'm testing it with my local sandbox if it works as I expect. During my play I figured out that backup was created successfully (as minimum I can look at it in the folder I set up in `Main()` like it described in your README). But when my app trying to restore data on `BeginRestoreBackup` method, I've got a `FabricException`:
```csharp
System.Fabric.FabricException: 'An error occurred during this operation.  Please check the trace logs for more details.'
Inner Exception
COMException: Exception from HRESULT: 0x80071D0A
```

StackTrace for FabricException:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceFabric.BackupRestore.BackupRestoreServiceInternalExtensions.<BeginRestoreBackup>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Storage.Storage.<RunAsync>d__5.MoveNext() in D:\Github\sf-backup\src\FabricApp\Storage\Storage.cs:line 78
```

StackTrace for Inner Exception (COMException):
```
   at System.Fabric.Interop.NativeClient.IFabricTestManagementClient3.EndStartPartitionDataLoss(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass20_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
```

**Code behavior:** 
I have two Reliable Dictionaries. The _system_ one where I store just one item with boolean value which indicates if storage is empty or not. And _storage_ where I store auto-generated 5 values (`<int, GUID>`). I expect that on the fist launch I will try to get my boolean indicator from _system_ dictionary and start filling my _storage_ up with 5 new values. Then I start `BeginCreateBackUp(BackupOption.Full` and clear my _storage_ (simulation of total data loss). Finally I start `BeginRestoreBackup` method and expect on service restart to get restored collection with all filled up data. But on `BeginRestoreBackup` I've got an Exception I wrote below.

My code in `RunAsync` method, just FYI:
```csharp
        protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            var system = await StateManager.GetOrAddAsync<IReliableDictionary<string, object>>("system.storage");
            var storage = await StateManager.GetOrAddAsync<IReliableDictionary<int, Guid>>("source");

            // check data existance
            bool isEmpty = true;
            using(var tx = StateManager.CreateTransaction())
            {
                var isEmptyResult = await system.TryGetValueAsync(tx, "is.empty");
                if (isEmptyResult.HasValue)
                {
                    var value = (bool)isEmptyResult.Value;
                    isEmpty = value;
                }

                await tx.CommitAsync();
            }

            if (isEmpty)
            {
                ServiceEventSource.Current.ServiceMessage(Context, "Fillup storage.");
                await FillUpStorageAsync(system, storage, cancellationToken);
                await ReadStorageAsync(storage, cancellationToken);

                ServiceEventSource.Current.ServiceMessage(Context, "Backup storage.");
                await BeginCreateBackup(BackupOption.Full);

                ServiceEventSource.Current.ServiceMessage(Context, "Clear storage.");
                await ClearStorageAsync(storage);

                ServiceEventSource.Current.ServiceMessage(Context, "Initiate backup storage.");
                var backups = (await ListBackups()).ToList();
                await BeginRestoreBackup(backups[0], DataLossMode.FullDataLoss);
            }
            else
            {
                ServiceEventSource.Current.ServiceMessage(Context, "Storage restored successfully.");
            }

            ServiceEventSource.Current.ServiceMessage(Context, "Enumerate storage.");
            await ReadStorageAsync(storage, cancellationToken);
        }
```

Maybe I'm tired or doing something wrong, but can you help me with this issue please?
Thank you so much!

**Comment by loekd** [comment]
Thanks for your detailed problem description. 

My initial guess would be that the backup process is not complete before you call `BeginRestoreBackup`. (The backup is created by Service Fabric in the background, which takes some time.)
Can you try adding some delay between backup and restore to see if that helps?

The exception handling needs a little work, to generate a clear error if the backup you're trying to restore is not found (yet).

**Comment by matterai** [comment]
@loekd after this line of code I've added `Task.Delay` with 5 minutes:
```csharp
await ClearStorageAsync(storage);
````
Unfortunately it didn't solve my issue:(

**UPD:** I've added you as a contributor to my private repo (`sf-backup`), you can look through the code if you need and try to run it.

**Comment by loekd** [comment]
I notice that you override `OnDataLossAsync` without calling base. I believe this is the cause that your backup isn't found.
Could you change your code, so that you create an implementation of `ICentralBackupStore` that saves its data into Azure Blob Storage, as a replacement for your custom `BackupRepository`. 
Pass this to the service from 'program.cs'.

**Comment by matterai** [comment]
@loekd sorry, didn't have time to check it, I remember and will be back as soon as I can (so many things to do at work). Do not close the thread, please! :)

**Comment by loekd** [comment]
closed due to inactivity
